/**
 * Mock notification data – used when the real API is unavailable or unauthenticated.
 * Mirrors the exact shape the real API returns.
 */

const now = Date.now();
const t = (minutesAgo) => new Date(now - minutesAgo * 60 * 1000).toISOString();

const MOCK_NOTIFICATIONS = [
  // ── PLACEMENT ──────────────────────────────────────────────────────────────
  {
    id: 1,
    title: "Goldman Sachs On-Campus Drive – URGENT",
    message: "Goldman Sachs on-campus recruitment drive has been moved to tomorrow 10 AM. All eligible students must update their resumes on the portal by tonight.",
    notification_type: "placement",
    created_at: t(0.5),
    is_read: false,
  },
  {
    id: 2,
    title: "Microsoft Pre-Placement Talk Tomorrow",
    message: "Microsoft pre-placement orientation is scheduled for tomorrow at 10 AM in the Main Auditorium. Attendance is mandatory for all interested candidates.",
    notification_type: "placement",
    created_at: t(2),
    is_read: false,
  },
  {
    id: 3,
    title: "Google On-Campus Drive – July 5th",
    message: "Google will conduct its placement drive on July 5th in the Main Hall. Register on the placement portal before July 3rd.",
    notification_type: "placement",
    created_at: t(90),
    is_read: false,
  },
  {
    id: 4,
    title: "Amazon SDE Internship – Register Now",
    message: "Amazon is hiring Software Development Engineer interns for 2025 batch. Registration deadline is June 30th. Apply through the placement portal.",
    notification_type: "placement",
    created_at: t(200),
    is_read: false,
  },
  {
    id: 5,
    title: "TCS NQT Results Announced",
    message: "TCS National Qualifier Test results have been announced. Qualified candidates will receive interview call letters within 48 hours.",
    notification_type: "placement",
    created_at: t(480),
    is_read: true,
  },
  {
    id: 6,
    title: "Infosys Walk-in Drive – July 8th",
    message: "Infosys is conducting a walk-in recruitment drive for the 2024 batch on July 8th. Bring 3 copies of your resume and all academic documents.",
    notification_type: "placement",
    created_at: t(720),
    is_read: false,
  },
  {
    id: 7,
    title: "Wipro Elite NTH – Registration Open",
    message: "Wipro Elite National Talent Hunt registration is now open. Last date to apply is July 10th. Visit wipro.com/careers for details.",
    notification_type: "placement",
    created_at: t(1440),
    is_read: true,
  },
  {
    id: 8,
    title: "Deloitte Consulting Interview Schedule",
    message: "Deloitte consulting interviews are scheduled for July 12-14. Shortlisted candidates check your emails for interview slots.",
    notification_type: "placement",
    created_at: t(2880),
    is_read: false,
  },
  // ── RESULT ─────────────────────────────────────────────────────────────────
  {
    id: 9,
    title: "Exam Timetable for July 2025 Released",
    message: "End-semester examination timetable for July 2025 is now published on the student portal. Please check your schedule and plan accordingly.",
    notification_type: "result",
    created_at: t(10),
    is_read: false,
  },
  {
    id: 10,
    title: "Semester 6 Results Published",
    message: "Semester 6 results for all branches are now available on the student portal. Log in with your credentials to view your grade sheet.",
    notification_type: "result",
    created_at: t(300),
    is_read: false,
  },
  {
    id: 11,
    title: "Mid-Term Grades Updated",
    message: "Mid-term assessment grades for all courses have been updated in the portal. Contact your subject teacher for any discrepancies.",
    notification_type: "result",
    created_at: t(600),
    is_read: true,
  },
  {
    id: 12,
    title: "Revaluation Results – CS301",
    message: "Revaluation results for CS301 (Data Structures) have been published. Students who applied for revaluation can check their updated marks.",
    notification_type: "result",
    created_at: t(1440),
    is_read: false,
  },
  {
    id: 13,
    title: "Internal Assessment Marks – May Batch",
    message: "Internal assessment marks for the May 2025 batch have been released. The final marks will be added to your semester grade.",
    notification_type: "result",
    created_at: t(2160),
    is_read: true,
  },
  {
    id: 14,
    title: "Supplementary Exam Results Out",
    message: "Results for the supplementary examinations held in May 2025 have been published. Visit the examination portal to view your results.",
    notification_type: "result",
    created_at: t(4320),
    is_read: false,
  },
  {
    id: 15,
    title: "CGPA Update – Spring Semester",
    message: "Your CGPA has been updated on the student portal reflecting Spring semester performance. Download your updated transcript from the portal.",
    notification_type: "result",
    created_at: t(5760),
    is_read: true,
  },
  // ── EVENT ──────────────────────────────────────────────────────────────────
  {
    id: 16,
    title: "Annual Tech Fest 2025 – Registration Open",
    message: "TechFest 2025 kicks off on July 20th. Register your teams for Hackathon, Coding Contest, Robotics, and more. Prizes worth ₹5 Lakhs!",
    notification_type: "event",
    created_at: t(5),
    is_read: false,
  },
  {
    id: 17,
    title: "Workshop: Machine Learning with PyTorch",
    message: "Free hands-on ML workshop on July 12th. Topics: Neural Networks, CNNs, Transfer Learning. Limited to 60 seats – register immediately.",
    notification_type: "event",
    created_at: t(60),
    is_read: false,
  },
  {
    id: 18,
    title: "24-Hour Hackathon – July 15th",
    message: "24-hour coding hackathon on July 15-16. Theme: AI for Social Good. Teams of 3-4. Cash prizes worth ₹1 Lakh. Register on the portal.",
    notification_type: "event",
    created_at: t(360),
    is_read: false,
  },
  {
    id: 19,
    title: "Guest Lecture: AI in Healthcare",
    message: "Dr. Anjali Mehta (AIIMS Research Director) will deliver a guest lecture on AI Applications in Medicine. July 9th, 3 PM, Main Auditorium.",
    notification_type: "event",
    created_at: t(420),
    is_read: true,
  },
  {
    id: 20,
    title: "Cultural Night – Spandan 2025",
    message: "Annual cultural night Spandan 2025 on July 18th. Passes available at the student affairs counter. Limited seats – get yours today!",
    notification_type: "event",
    created_at: t(1080),
    is_read: false,
  },
  {
    id: 21,
    title: "NSS Blood Donation Camp – July 7th",
    message: "NSS unit is organizing a blood donation camp on July 7th at the college health centre. All healthy students are encouraged to participate.",
    notification_type: "event",
    created_at: t(1800),
    is_read: true,
  },
  {
    id: 22,
    title: "Entrepreneurship Summit – ECell",
    message: "E-Cell presents the Annual Entrepreneurship Summit 2025. Speakers from top startups and VCs. July 22nd, 9 AM. Register on ecell.org.",
    notification_type: "event",
    created_at: t(2400),
    is_read: false,
  },
  {
    id: 23,
    title: "Sports Meet Registration Open",
    message: "Annual inter-college sports meet registration is open. Events include cricket, football, basketball, badminton, and athletics. Last date: July 5th.",
    notification_type: "event",
    created_at: t(3600),
    is_read: false,
  },
  {
    id: 24,
    title: "Photography Workshop – July 11th",
    message: "Learn professional photography and post-processing. Workshop on July 11th by alumni photographer Rohan Verma. Free registration for first 30.",
    notification_type: "event",
    created_at: t(4800),
    is_read: true,
  },
  {
    id: 25,
    title: "Library Extended Hours – Exam Season",
    message: "Library will remain open until midnight from July 1-20 to support exam preparation. Study rooms can be booked via the library portal.",
    notification_type: "event",
    created_at: t(6000),
    is_read: false,
  },
  // ── more PLACEMENT ─────────────────────────────────────────────────────────
  {
    id: 26,
    title: "Accenture Recruitment – July 20th",
    message: "Accenture campus recruitment drive scheduled for July 20th. Eligible: All branches, 60%+ aggregate. Register by July 15th on placement portal.",
    notification_type: "placement",
    created_at: t(3200),
    is_read: false,
  },
  {
    id: 27,
    title: "IBM Internship Applications Open",
    message: "IBM is accepting internship applications for its Cloud and AI division. Duration: 6 months. Apply through the placement portal by July 12th.",
    notification_type: "placement",
    created_at: t(5000),
    is_read: true,
  },
  {
    id: 28,
    title: "Capgemini Off-Campus Drive",
    message: "Capgemini off-campus recruitment for 2024 and 2025 passouts. Online test on July 18th. Register at capgemini.com/careers.",
    notification_type: "placement",
    created_at: t(7200),
    is_read: false,
  },
  // ── more RESULT ────────────────────────────────────────────────────────────
  {
    id: 29,
    title: "Project Viva Schedule – Final Year",
    message: "Final year project viva schedule has been uploaded. Check the academic portal for your assigned date, time, and panel. Starts July 8th.",
    notification_type: "result",
    created_at: t(900),
    is_read: false,
  },
  {
    id: 30,
    title: "Scholarship Result – Merit List",
    message: "Merit-based scholarship results for 2025-26 academic year are published. Selected students will receive communication from the finance office.",
    notification_type: "result",
    created_at: t(3000),
    is_read: true,
  },
];

export default MOCK_NOTIFICATIONS;
